Implemented support for transaction API.
tnapf/SQLDriver pull request #8
Opened 2023-07-04 19:34 UTC by freezemage0

- Added `@throws` tags where needed.
- Removed unused static `PDODriver::$instance` property;
- Implemented `DriverException::createFromPdo()` named constructor for convenience.

Fixes #2 and #5

2023-07-04 19:41 UTC, xHeaven requested changes

2023-07-04 19:41 UTC, xHeaven commented on src/PDODriver.php
> +    public function begin(): bool
Where is the `return`?

2023-07-04 19:41 UTC, xHeaven commented on src/PDODriver.php
> +    public function commit(): bool
Where is the `return`?

2023-07-04 19:41 UTC, xHeaven commented on src/PDODriver.php
> +    public function rollback(): bool
Where is the `return`?

2023-07-04 19:44 UTC, xHeaven approved these changes
LGTM.

2023-07-05 23:26 UTC, CommandString approved these changes

2023-07-06 16:42 UTC, merged